# Generated by Django 6.0.1 on 2026-02-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "isdeletedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.isdeletedmodel",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=25, null=True, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=25, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="avatars/default.jpg", null=True, upload_to="avatars/"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("SELLER", "SELLER"), ("BUYER", "BUYER")],
                        default="BUYER",
                        max_length=6,
                        verbose_name="Account type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("common.isdeletedmodel", models.Model),
        ),
    ]
