# Generated by Django 6.0.1 on 2026-02-02 21:21

import autoslug.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="category_images/")),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "isdeletedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.isdeletedmodel",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True, editable=False, populate_from="name"
                    ),
                ),
                ("desc", models.TextField()),
                (
                    "price_old",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("price_current", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_stock", models.IntegerField(default=5)),
                ("image1", models.ImageField(upload_to="product_images/")),
                ("image2", models.ImageField(blank=True, upload_to="product_images/")),
                ("image3", models.ImageField(blank=True, upload_to="product_images/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("common.isdeletedmodel",),
        ),
    ]
